vim9script

if empty($XDG_CACHE_HOME)  | $XDG_CACHE_HOME  = $HOME .. "/.cache"       | endif
if empty($XDG_CONFIG_HOME) | $XDG_CONFIG_HOME = $HOME .. "/.config"      | endif
if empty($XDG_DATA_HOME)   | $XDG_DATA_HOME   = $HOME .. "/.local/share" | endif
if empty($XDG_STATE_HOME)  | $XDG_STATE_HOME  = $HOME .. "/.local/state" | endif

set runtimepath^=$XDG_CONFIG_HOME/vim

# Setup baseline settings
runtime init/10_sensual.vim
runtime init/20_crash_tolerance.vim
runtime init/50_ale.vim
runtime init/50_asciidoctor.vim
runtime init/50_autocmd.vim
runtime init/50_fern.vim
runtime init/50_fzf.vim
runtime init/50_hooks.vim
runtime init/50_is.vim
runtime init/50_lightline.vim
runtime init/50_mappings.vim
runtime init/50_ruby.vim
runtime init/50_theme.vim
