abbr --add be  "bundle exec"
abbr --add bi  "bundle install"
abbr --add bu  "bundle update"
abbr --add bo  "bundle open"
abbr --add ror "bundle exec rails"
abbr --add om  "overmind"
abbr --add gbv "git branch --verbose --verbose"
abbr --add gfp "git fetch --prune"
abbr --add gri "git rebase --interactive"
abbr --add av  "aws-vault"
